/**
 * 機器可讀錯誤碼（enum，命名規則：模組_錯誤類型）。
 * 與 docs/openapi.yaml 各端點範例保持一致；新增時同步更新規格。
 */
export enum ErrorCode {
  // common
  COMMON_VALIDATION_FAILED = 'COMMON_VALIDATION_FAILED',
  COMMON_INTERNAL_ERROR = 'COMMON_INTERNAL_ERROR',

  // auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_ALREADY_USED = 'AUTH_EMAIL_ALREADY_USED',
  AUTH_USERNAME_TAKEN = 'AUTH_USERNAME_TAKEN',
  AUTH_INVITE_CODE_INVALID = 'AUTH_INVITE_CODE_INVALID',
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_ROLE_NOT_ALLOWED = 'AUTH_ROLE_NOT_ALLOWED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',

  // class / student
  CLASS_NOT_FOUND = 'CLASS_NOT_FOUND',
  CLASS_ALREADY_ENROLLED = 'CLASS_ALREADY_ENROLLED',
  STUDENT_NOT_FOUND = 'STUDENT_NOT_FOUND',

  // assignment / submission
  ASSIGNMENT_NOT_FOUND = 'ASSIGNMENT_NOT_FOUND',
  ASSIGNMENT_INVALID_TRANSITION = 'ASSIGNMENT_INVALID_TRANSITION',
  SUBMISSION_NOT_FOUND = 'SUBMISSION_NOT_FOUND',
  SUBMISSION_NOT_ACCEPTABLE = 'SUBMISSION_NOT_ACCEPTABLE',
  SUBMISSION_ALREADY_RETURNED = 'SUBMISSION_ALREADY_RETURNED',

  // files
  ATTACHMENT_NOT_FOUND = 'ATTACHMENT_NOT_FOUND',
  ATTACHMENT_REJECTED = 'ATTACHMENT_REJECTED',

  // analysis（對應 docs/analysis-service.md §2.4）
  ANALYSIS_NOT_FOUND = 'ANALYSIS_NOT_FOUND',
  ANALYSIS_ALREADY_RUNNING = 'ANALYSIS_ALREADY_RUNNING',
  ANALYSIS_NO_CONTENT = 'ANALYSIS_NO_CONTENT',
  ANALYSIS_ENGINE_UNAVAILABLE = 'ANALYSIS_ENGINE_UNAVAILABLE',
  ANALYSIS_OCR_FAILED = 'ANALYSIS_OCR_FAILED',
  ANALYSIS_FAILED = 'ANALYSIS_FAILED',

  // grades
  GRADE_CATEGORY_NOT_FOUND = 'GRADE_CATEGORY_NOT_FOUND',
  GRADE_WEIGHT_EXCEEDED = 'GRADE_WEIGHT_EXCEEDED',
  GRADE_CATEGORY_NAME_TAKEN = 'GRADE_CATEGORY_NAME_TAKEN',
  GRADE_ENTRY_STUDENT_INVALID = 'GRADE_ENTRY_STUDENT_INVALID',

  // notifications / analytics
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
  ANALYTICS_INVALID_ASSIGNMENT_PAIR = 'ANALYTICS_INVALID_ASSIGNMENT_PAIR',
}
