/**
 * 機器可讀錯誤碼（enum，命名規則：模組_錯誤類型）。
 * 與 docs/openapi.yaml 各端點範例保持一致；新增時同步更新規格。
 */
export enum ErrorCode {
  // common
  COMMON_VALIDATION_FAILED = 'COMMON_VALIDATION_FAILED',
  COMMON_INTERNAL_ERROR = 'COMMON_INTERNAL_ERROR',

  // auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_ALREADY_USED = 'AUTH_EMAIL_ALREADY_USED',
  AUTH_USERNAME_TAKEN = 'AUTH_USERNAME_TAKEN',
  AUTH_INVITE_CODE_INVALID = 'AUTH_INVITE_CODE_INVALID',
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_ROLE_NOT_ALLOWED = 'AUTH_ROLE_NOT_ALLOWED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',

  // class / student
  CLASS_NOT_FOUND = 'CLASS_NOT_FOUND',
  CLASS_ALREADY_ENROLLED = 'CLASS_ALREADY_ENROLLED',
  STUDENT_NOT_FOUND = 'STUDENT_NOT_FOUND',
}
